# Generated by Django 4.1.5 on 2023-03-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'feature',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProvinceA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'province_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProvinceB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'province_b',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProvinceOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'province_other',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('is_211', models.IntegerField()),
                ('type_name', models.CharField(blank=True, max_length=50, null=True)),
                ('type_school_name', models.CharField(max_length=50)),
                ('province_area', models.CharField(max_length=10)),
                ('syl', models.IntegerField(blank=True, null=True)),
                ('school_name', models.CharField(max_length=50)),
                ('clicks', models.IntegerField(blank=True, null=True)),
                ('is_985', models.IntegerField(blank=True, null=True)),
                ('is_zihuaxian', models.IntegerField(blank=True, null=True)),
                ('rk_rank', models.IntegerField(blank=True, null=True)),
                ('province_name', models.CharField(blank=True, max_length=20, null=True)),
                ('is_ads', models.IntegerField(blank=True, null=True)),
                ('school_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'school_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learntype', models.CharField(db_column='learnType', max_length=10)),
                ('major_code', models.CharField(max_length=20)),
                ('major_name', models.TextField()),
                ('total', models.CharField(blank=True, max_length=10, null=True)),
                ('politics', models.TextField(blank=True, null=True)),
                ('english', models.TextField(blank=True, null=True)),
                ('procourse', models.TextField(blank=True, null=True)),
                ('procourese2', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('school_name', models.TextField(blank=True, null=True)),
                ('school_tel', models.TextField(blank=True, null=True)),
                ('school_email', models.TextField(blank=True, null=True)),
                ('school_web', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'school_score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'school_type',
                'managed': False,
            },
        ),
    ]
