# Generated by Django 4.1.5 on 2023-03-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showSchool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotSchoolSearch',
            fields=[
                ('school_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'hotSearchSchool',
                'managed': True,
            },
        ),
    ]
