# Generated by Django 4.1.5 on 2023-04-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showSchool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryLine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('school_year', models.IntegerField()),
                ('major_name', models.TextField()),
                ('total', models.IntegerField()),
                ('single_100', models.IntegerField()),
                ('single_150', models.IntegerField()),
                ('degree_type', models.IntegerField()),
                ('area_type', models.CharField(max_length=50)),
                ('code', models.TextField()),
            ],
            options={
                'db_table': 'countryline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('content', models.TextField()),
                ('username', models.CharField(max_length=50)),
                ('number', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='articlePhoto/')),
                ('like', models.IntegerField()),
                ('cur_time', models.TextField(null=True)),
            ],
            options={
                'db_table': 'article',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='article_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('article_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'article_comment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('image', models.ImageField(upload_to='photos/')),
            ],
            options={
                'db_table': 'userAvator',
                'managed': True,
            },
        ),
    ]
