# Generated by Django 4.1.5 on 2023-04-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showSchool', '0002_countryline_article_article_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
