# Generated by Django 4.1.5 on 2023-03-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showSchool', '0003_alter_hotschoolsearch_school_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('userPassword', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'userInfo',
                'managed': True,
            },
        ),
    ]
