# Generated by Django 4.1.5 on 2023-03-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showSchool', '0006_school_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='major',
            fields=[
                ('major_name', models.CharField(max_length=50)),
                ('major_code', models.CharField(max_length=50)),
                ('major_class', models.CharField(max_length=10)),
                ('level1_name', models.CharField(max_length=50)),
                ('level2_name', models.CharField(max_length=50)),
                ('spe_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'major',
                'managed': True,
            },
        ),
    ]
