# Generated by Django 4.1.5 on 2023-04-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article2',
            fields=[
                ('content', models.TextField()),
                ('username', models.CharField(max_length=50)),
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='articlePhoto/')),
                ('like', models.IntegerField()),
                ('my_date', models.TextField()),
            ],
            options={
                'db_table': 'article',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='article_comment2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('article_id', models.IntegerField()),
            ],
            options={
                'db_table': 'article_comment',
                'managed': True,
            },
        ),
    ]
