# Generated by Django 4.1.5 on 2023-04-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='article2',
        ),
        migrations.DeleteModel(
            name='article_comment2',
        ),
    ]
